//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod tb_action;
pub mod tb_category;
pub mod tb_product;
pub mod tb_reason;
pub mod tb_report;
pub mod tb_user;

pub mod dtos;
pub mod enums;
