//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub name: String,
    pub quantity: u64,
    pub min_quantity: u64,
    pub category_id: u64,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_category::Entity",
        from = "Column::CategoryId",
        to = "super::tb_category::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    TbCategory,
    #[sea_orm(has_many = "super::tb_report::Entity")]
    TbReport,
}

impl Related<super::tb_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbCategory.def()
    }
}

impl Related<super::tb_report::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbReport.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
