//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_report")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub date: DateTime,
    pub quantity: u64,
    pub refund_reason_id: u64,
    pub product_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_product::Entity",
        from = "Column::ProductId",
        to = "super::tb_product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbProduct,
    #[sea_orm(
        belongs_to = "super::tb_refund_reasons::Entity",
        from = "Column::RefundReasonId",
        to = "super::tb_refund_reasons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbRefundReasons,
}

impl Related<super::tb_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbProduct.def()
    }
}

impl Related<super::tb_refund_reasons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbRefundReasons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
