//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub username: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: String,
    pub role_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_role::Entity",
        from = "Column::RoleId",
        to = "super::tb_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbRole,
}

impl Related<super::tb_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
